repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-added-large-files
        args: ["--maxkb=1024"]
      - id: check-merge-conflict
      - id: detect-aws-credentials
        args:
          - "--allow-missing-credentials"
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: fix-byte-order-marker
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
      - id: check-yaml
        args:
          - "--allow-multiple-documents"
  - repo: https://github.com/sirosen/texthooks
    rev: 0.6.6
    hooks:
      - id: fix-smartquotes
  - repo: https://github.com/renovatebot/pre-commit-hooks
    rev: 38.27.0
    hooks:
      - id: renovate-config-validator
