default_branch: "main"
web_commit_signoff_required: true
has_issues: true
has_projects: true
has_wiki: true
has_downloads: true
has_pages: false
has_discussions: true
allow_squash_merge: true
allow_merge_commit: false
allow_rebase_merge: false
allow_auto_merge: true
delete_branch_on_merge: true
allow_update_branch: true
squash_merge_commit_title: "PR_TITLE"
squash_merge_commit_message: "BLANK"
security_and_analysis:
  secret_scanning:
    status: "enabled"
  secret_scanning_push_protection:
    status: "enabled"
  dependabot_security_updates:
    status: "enabled"
  secret_scanning_non_provider_patterns:
    status: "disabled"
  secret_scanning_validity_checks:
    status: "disabled"
